artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Nik-Nikhil1910/datasets/raw/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/data_ingestion/WineQT.csv"
  preprocessing_steps:
    - name: "scaler"
      type: "StandardScaler"
    - name: "log_transform"
      type: "LogTransform"  # A new entry for log transformation


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/transformed_train_data.csv
  test_data_path: artifacts/data_transformation/transformed_test_data.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/transformed_test_data.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
